name: windows pytest

on: [push, pull_request]

jobs:
  test:
    name: windows py39
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9


      # strategy borrowed from vispy for installing opengl libs on windows
      - name: Install Windows OpenGL
        if: runner.os == 'Windows'
        run: |
          git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
          powershell gl-ci-helpers/appveyor/install_opengl.ps1


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install napari

      - name: Install yt-napari
          run: python -m pip install -e .

      # this runs the platform-specific tests declared in tox.ini
      - name: Test with pytest
        run: |
          python --version
          pytest .
